library/api/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from library.api.views import api_detail_authorview, api_detail_bookview, api_detail_orderview, api_book_create, api_book_delete, api_detail_bookmodify, api_student_list, api_sub_category_list

app_name = 'library'

urlpatterns = [
    path("authors/<nm>/", api_detail_authorview),
    path("orders/<oid>/",api_detail_orderview),
    path("books/<bknm>", api_detail_bookview),
    path("books/update/<bknm>", api_detail_bookmodify),
    path("book/delete/<bknm>", api_book_delete),
    path("book/new/create", api_book_create),
    path("std_details/", api_student_list),
    path("subcat/<mc>/", api_sub_category_list)


]

library/urls.py
from django.urls import include, path
from . import views

urlpatterns = [

	path("", views.home, name="home"),
	path("books/", views.books, name="books"),
    #path("books", views.get_books, name="get_books"),
    path("load_subcats/", views.load_subCat, name="ajax_load_subcat"),
    path("signup/", views.signup_form, name="signup"),
    path("login/", views.login_page, name="login"),
    path("logout/", views.logoutUser, name="logout"),
    path('signup_ajax', views.signup_ajax, name="signup_ajax"),
    path('book/<int:pk>', views.book_detail_view, name="book-detail"),
    path('orders/', views.book_orders, name="ajax_orders"),
    path('student_orders/', views.student_orders, name="student_orders"),
    path('create_book/', views.AddBook, name="create_book"),
    path('delete_book/', views.RemoveBook, name="delete_book")
]


weblibrary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("library.urls")),

    #rest framework urls
    path("api/library/", include("library.api.urls", "library_api")),
]

library/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import SET_NULL
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
# Create your models here.
class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True)
    roll_num = models.CharField(max_length=200, null=True)
    studying = models.CharField(max_length=200, null=True)
    branch = models.CharField(max_length=200, null=True)
    pyr = models.CharField(max_length=200,null=True)

    def __str__(self):
        return str(self.user.username)
    
    @receiver(post_save, sender=User)
    def create_student(sender, instance, created, **kwargs):
        if created:
            Student.objects.create(user=instance)
        instance.student.save()     
    
    

class Author(models.Model):
    name = models.CharField(max_length=200, null=True)
    
    def __str__(self):
        return self.name

class BookMainCategory(models.Model):
    category_name = models.CharField(max_length=20)
     
    def __str__(self):
        return self.category_name

class BookSubCategory(models.Model):
    sub_category_name = models.CharField(max_length=100)
    main_category = models.ForeignKey(BookMainCategory, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.sub_category_name    

class StudentMainTable(models.Model):
    stdid = models.AutoField(primary_key=True, blank=True)
    name = models.TextField()
    email_id = models.TextField(blank=True, null=True)
    degree = models.TextField()
    branch = models.TextField()
    persuing_year = models.TextField()
    doj = models.TextField()

    class Meta:
        managed = False
        db_table = 'student'
    def __str__(self):
        return self.name    
        
class Book(models.Model):
    isbn_num = models.CharField("ISBN", max_length=20, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    title = models.CharField(max_length=100, null=True)
    author = models.ForeignKey(Author,  on_delete=models.SET_NULL, null=True)
    summary = models.CharField(max_length=200, null=True, blank=True)
    main_category = models.ForeignKey(BookMainCategory, on_delete=models.CASCADE, null=True)
    sub_category = models.ForeignKey(BookSubCategory, on_delete=models.CASCADE, null=True)
    book_count = models.IntegerField(null=False, default=0)
 
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

class Order(models.Model):
    order_id = models.AutoField(primary_key=True)   
    std = models.ForeignKey(Student, null=True, on_delete=SET_NULL)
    book = models.ForeignKey(Book, null=True, on_delete=SET_NULL)
    date_created = models.DateField(auto_now_add=True, null=True)

    def __str__(self):
        return str(self.order_id)

library/forms.py
from django.forms import ModelForm
from .models import BookSubCategory, Book, StudentMainTable
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError
        
class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = {'main_category', 'sub_category'}
     
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['sub_category'].queryset = BookSubCategory.objects.none()
        
        if 'main_category' in self.data:
            try:
                main_category_id = int(self.data.get('main_category'))
                self.fields['sub_category'].queryset = BookSubCategory.objects.filter(main_category_id=main_category_id)#.order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['sub_category'].queryset = self.instance.main_category.sub_category_set#.order_by('name')

class SignupForm1(UserCreationForm):
    rollNumber = forms.CharField(max_length=200, help_text="Roll Number of the student", widget=forms.TextInput(attrs={'placeholder': 'Roll Number'}))
    username = forms.CharField(max_length=200, help_text= "Name of the student", widget=forms.TextInput(attrs={'placeholder': 'Student Name'}))
    studying = forms.CharField(max_length=200, help_text="Degree of the student", widget=forms.TextInput(attrs={'placeholder': 'Degree'}))
    branch = forms.CharField(max_length=200, help_text="Branch of the student", widget=forms.TextInput(attrs={'placeholder': 'Branch'}))
    persuingyear = forms.CharField(help_text="Persuing year fo the student", widget=forms.TextInput(attrs={'placeholder': 'pursuing year'}))
    email = forms.EmailField(max_length=100, help_text="Student email", widget=forms.TextInput(attrs={'placeholder': 'Email Address'}))
    class Meta:
        model = User
        fields = ('rollNumber', 'username',  'studying', 'branch', 'persuingyear', 'email', 'password1', 'password2')
        #fields = ('username', 'email', 'password1', 'password2')


    def clean(self):
        cleaned_data = super(SignupForm1, self).clean()
        rollnum = self.cleaned_data.get("rollNumber")
        un = self.cleaned_data.get("username")
        em = self.cleaned_data.get("email")
        print(em)
        print(un)
        print(rollnum)
        rnqs = StudentMainTable.objects.filter(stdid=rollnum)
        print(rnqs)
        if rnqs.exists() :
            for obj in rnqs:
                nm = obj.name
            if nm == un:    
                return self.cleaned_data
            else:
                raise forms.ValidationError("User name mismatch. The specified roll number has different user name")            
        else:
            raise forms.ValidationError("The roll number doesnt exist in the main db")    

class CreateBook(ModelForm):
    class Meta:
        model = Book
        fields = {'isbn_num','title','author','summary','main_category', 'sub_category','book_count'}
     
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['sub_category'].queryset = BookSubCategory.objects.none()
        
        if 'main_category' in self.data:
            try:
                main_category_id = int(self.data.get('main_category'))
                self.fields['sub_category'].queryset = BookSubCategory.objects.filter(main_category_id=main_category_id)#.order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['sub_category'].queryset = self.instance.main_category.sub_category_set#.order_by('name') 

class DeleteBook(ModelForm):
    title = forms.CharField(max_length=200, help_text="Book Name", widget=forms.TextInput(attrs={'placeholder': 'Enter Book Name'}))
    class Meta:
        model = Book
        fields = {'title'}
        
        
        

library/api/views.py
from rest_framework import serializers, status, permissions
from rest_framework import response
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes

from library.models import Author, BookSubCategory, Order, Book, StudentMainTable, Student, BookMainCategory
from library.api.Serializer import AuthorSerializer, OrderSerializer, BookSerializer, StudentSerializer, SubCategorySerializer

@api_view(['GET',])
@permission_classes((permissions.AllowAny,))
def api_detail_authorview(request, nm):
    try:
        athr = Author.objects.get(name=nm)
    except Author.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    if request.method == "GET":
        serializer = AuthorSerializer(athr)
        return Response(serializer.data)

@api_view(['GET',])
@permission_classes((permissions.AllowAny,))
def api_detail_orderview(request, oid):
    try:
        ordr = Order.objects.get(order_id = oid)
    except Order.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    if request.method == 'GET':
        srl = OrderSerializer(ordr)
        return Response(srl.data)

@api_view(['GET',])
@permission_classes((permissions.AllowAny,))
def api_detail_bookview(request, bknm):
    try:
        bk = Book.objects.get(title = bknm)
    except Book.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    if request.method == 'GET':
        bk_srl = BookSerializer(bk)
        return Response(bk_srl.data)

@api_view(['PUT',])
@permission_classes((permissions.AllowAny,))
def api_detail_bookmodify(request, bknm):
    try:
        bk = Book.objects.get(title = bknm)
    except Book.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    if request.method == 'PUT':
        bk_srl = BookSerializer(bk, data=request.data)
        data = {}
        if bk_srl.is_valid():
            bk_srl.save()
            data['Success'] = "Update successful"
            return Response(data=data)
        return Response(bk_srl.errors, status=status.HTTP_400_BAD_REQUEST)    
        
@api_view(['DELETE',])
@permission_classes((permissions.AllowAny,))
def api_book_delete(request, bknm):
    try:
        bk = Book.objects.get(title = bknm)
    except Book.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    if request.method == "DELETE":
        opr = bk.delete()
        data = {}
        if opr:
            data['Success'] = "Object deleted successfully"
        else:
            data['Failure'] = "Object delete failed"
        return Response(data=data)

@api_view(['POST',])
@permission_classes((permissions.AllowAny,))
def api_book_create(request):
    try:
        author = Author.objects.get(pk=11)
        bkc = Book(author=author)
        if request.method == "POST":
            bk_srl = BookSerializer(bkc, data=request.data)
            if bk_srl.is_valid():
                bk_srl.save()
                return Response(bk_srl.data, status=status.HTTP_201_CREATED)
            return Response(bk_srl.errors, status=status.HTTP_400_BAD_REQUEST)
    except Exception as e:
        print(e)

@api_view(['GET'])
@permission_classes((permissions.AllowAny,))
def api_student_list(request):
    std_dts = Student.objects.all()
    std = StudentSerializer(std_dts, many=True)
    return Response(std.data)
'''
@api_view(['GET'])
@permission_classes((permissions.AllowAny,))
def api_main_category_list(request):
    main_lst = BookMainCategory.objects.all()
    main_slr = MainCategorySerializer(main_lst, many=True)
    return Response(main_slr.data)
'''
@api_view(['GET'])
@permission_classes((permissions.AllowAny,))
def api_sub_category_list(request, mc):
    sub_cat = BookSubCategory.objects.filter(main_category_id = mc)
    sub_slr = SubCategorySerializer(sub_cat, many=True)
    return Response(sub_slr.data)



            
                

library/templates/book_detail.html
{% extends "main.html" %}

{% block content %}
<body>
  <h1>Title: {{ book.title }}</h1>
  <div >
  <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn_num }}</p>
</div>
  <div>
    {% if book.book_count > 0 %}
      <p> <strong> Available: </strong> {{book.book_count}} </p>
      <button class="btn btn-info" type="button" id="{{book.title}}">Order</button>
    {% else %}
      <p>No Books available presently</p>
    {% endif %}  
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
  $('.btn-info').click(function() {
    var id = this.id
    $url = 0
    alert(id)
  })
  </script>
  </body>
  {% endblock %}

library/templates/bookinstance.html
<table>
    <th>
        <tr>book</tr>
        <tr>count</tr>
{% for i in bi %}
    <tr>
    <td>{{i.book.title}}</td>
    <td>{{i.objects.filter(book__title=i.book.title).count()}}</td>
    </tr>
{% endfor %}    

library/templates/books.html
{% extends "main.html" %}
{% block content %}
<style>
	.hidden {
		display: none;
	}
</style>
<body>
	<div>
		<table style="width: auto;" class="table table-sm table-dark">
			<thead>
				<tr>
					<th scope="col" >Student Name</th>
					<th scope="col">Roll Number</th>
					<th scope="col">Degree</th>
					<th scope="col">Branch</th>
					<th scope="col">Persuing Year</th>
				</tr>
			</thead>
			{% for std in std_details %}
			<tr>
				<td>{{std.name}}</td>
				<td>{{std.roll_num}}</td>
				<td>{{std.studying}}</td>
				<td>{{std.branch}}</td>
				<td>{{std.pyr}}</td>
			</tr>
			{% endfor %}
		</table>
	</div>
	
	{% load crispy_forms_tags %} 

	
		<form action="" id="bookform" data-subcat-url="{% url 'ajax_load_subcat' %}" method="POST">
			{% csrf_token %}
			<div class="row"> 
				<div class="col-2">
					{{form.main_category | as_crispy_field}}
				</div>
				<div class="col-2">
					{{form.sub_category | as_crispy_field}}
				</div>
			</div>
			<input class="btn btn-primary" type="Submit" name="Submit">
		
		</form>
	
	<div >
		<span>
			<div >
			{% if fb %}
			<table class="table table-sm"> 
				<thead>
					<tr>
						<th scope="col-2">books</th>
						<th scope="col-2">Available </th>
						<th scope="col-2">Order</th>
					</tr>	
				</thead>
					{% for i in fb %}
					<tr> <td ><a href="{{i.get_absolute_url}}">{{i.title}} </a></td>
					 <td > {{i.book_count}} </td>
					<td > <button class="btn btn-info" type="button" id="{{i.title}}">Order</button> </td>
					</tr>
					{% endfor %}
			</table>
			{% endif %}
			</div>
		</span>
	</div>
	<div id="div" class="hidden">	
	<button class="btn btn-secondary" type="button" >checkout</button>
	</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
$("#id_main_category").change(function() {
	console.log("hi welcome")
	url = $('#bookform').attr('data-subcat-url');
	const maincat = $(this).val();
	console.log(maincat);
	console.log(url)
	$.ajax({
		url: url,
		data: {'main_cat': maincat},
		success:function(data){
			$('#id_sub_category').html(data);
			}
		});	
});

$('.btn-info').click(function() {
	var id = this.id
	var url = "{% url 'ajax_orders' %}"
	console.log(url)
	alert(id)
	$.ajax({
		url:url,
		data: {"book_name": id},
		success:function(data){
			console.log("success")
			alert(data.msg)
			if($('#div').is(":visible"))
			{
				console.log("hi")
			}
			else{
				
				$('#div').toggle()
			}
			
		},

		error:function(data){
			alert(data.msg)
		}
	})
	
})
</script>
</body>
{% endblock %}

	

library/templates/create_book.html
{% extends "main.html" %}
{% block content %}
<style>
	.hidden {
		display: none;
	}
</style>
<body>
	
	
	{% load crispy_forms_tags %} 

	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">ADD BOOK</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
		<form action="" id="createbookform" data-subcat-url="{% url 'ajax_load_subcat' %}" method="POST">
			{% csrf_token %}
			
			<div class="row"> 
                <div class="col-2">
					{{form.isbn_num | as_crispy_field}}
				</div>
                <div class="col-2">
					{{form.title | as_crispy_field}}
				</div>
                <div class="col-2">
					{{form.author | as_crispy_field}}
				</div>
                <div class="col-2">
					{{form.summary | as_crispy_field}}
				</div>
				<div class="col-2">
					{{form.main_category | as_crispy_field}}
				</div>
				<div class="col-2">
					{{form.sub_category | as_crispy_field}}
				</div>
                <div class="col-2">
					{{form.book_count | as_crispy_field}}
				</div>
			</div>
			
			<input class="btn btn-info" type="submit" id="newBook" value="Add Book"> 

		</div>
			</div>
		</div>
	</div>
	
		</form>
	
	
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
$("#id_main_category").change(function() {
	console.log("hi welcome")
	//url = $('#createbookform').attr('data-subcat-url');
	const maincat = $(this).val();
	url = "http://127.0.0.1:8000/api/library/subcat/"+maincat
	
	console.log(maincat);
	console.log(url)
	$.ajax({
		url: url,
		dataType: 'JSON',
		success:function(data){
			//$('#id_sub_category').html(data);
			$("#id_sub_category").empty()
			var inrow = $("<option>-------</option>")
			$("id_sub_category").append(inrow)
			for(var i=0; i<data.length;i++)
				{
					var row = $("<option>"+data[i].sub_category_name+"</option>");
					$("#id_sub_category").append(row);
				}
			}
		});	
});

$('.btn-info').click(function() {
	
	var url = "{% url 'create_book' %}"
	console.log(url)
	
	$.ajax({
		url:url,
		
		success:function(){
			console.log("success")
			alert(data.msg)
			
		},

		error:function(data){
			alert(data.msg)
		}
	})
	
})

</script>
</body>
{% endblock %}

	

library/templates/dashboard.html
{% extends "main.html" %}
{% block content %}
<div class="row">
  <div class="col-md-5">
	<h5> Student Details : </h5>
	<hr>
	<div class="card card-body" id="UserTable">
		<table class="table table-sm" id="std_details">
			<tr>
				<th>Name</th>
				<th>Roll Number</th>
				<th>Studying</th>
				<th>Branch</th>
				<th>Pursuing Yr</th>
				<th>Ordered Books</th>
				<!--<th> Action </th>-->
			</tr>
			<!--{% for i in st %}
			<tr>
				<td> {{i.name}} </td>
				<td>{{i.roll_num}}</td>
				<td>{{i.studying}}</td>
				<td>{{i.branch}}</td>
				<td>{{i.pyr}}</td>
				<td>{{i.order_set.all.count}}</td>
				<td><button><a href="#">Modify</a> / <a href="#">Delete</a></button></td>
			</tr>
			{% endfor %}-->
		</table>
	</div>
	<br>
	<div  class="col-md-7">
		<table class="table table-sm">
			<tr>
			<th>Add/Delete Book</th>
			</tr>
			<tr>
				<td><a href="{% url 'create_book' %}">Add Book</a></td>
				<td><a href="{% url 'delete_book' %}">Delete Book</a></td>
			</tr>
		</table>
	</div>
	</div>
</div>	
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
	$(document).ready(function()
	{
		$.ajax({
			url: "http://127.0.0.1:8000/api/library/std_details/",
			dataType: 'JSON',
			success:function(data){
				
				for(var i=0; i<data.length;i++)
				{
					var row = $("<tr><td>"+data[i].name+"</td><td>"+data[i].roll_num+"</td><td>"+data[i].studying+"</td><td>"+data[i].branch+"</td><td>"+data[i].pyr+"</td><td>"+data[i].books_ordered+"</td></tr>");
					$("#std_details").append(row);
					
				}
			}
		})
	})
</script>
{% endblock %}

library/templates/delete_book.html
{% extends "main.html" %}
{% block content %}
<style>
	.hidden {
		display: none;
	}
</style>
<body>
	 

	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REMOVE BOOK</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
		<form action="" id="deletebookform" method="POST">
			{% csrf_token %}
			
			
			{{ form.title }}
			
			
			<input class="btn btn-info" type="submit" id="removeBook" value="Delete Book"> 

		</div>
			</div>
		</div>
	</div>
	
		</form>
	
	
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>

</script>
</body>
{% endblock %}

	

library/templates/get_books.html
{% extends "main.html" %}
{% block content %}
	<table>
	<th>books</th>
	{% for i in fb %}
	<tr> <td>{{i.title}} </td></tr>
	{% endfor %}
	</table>
{% endblock %}

library/templates/home.html
{% extends "main.html" %}
	{% block content %}
		<h1> home </h1>
	{% endblock %}	
	</body>
</html>

library/templates/signup.html


<!DOCTYPE html>
<html>
    
<head>
	<title>Register</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="" id="signupform" data-url="{% url 'signup_ajax' %}">
                                                {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{ form.rollNumber }}
						</div>	
						
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{ form.username }}
						</div>
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-hashtag"></i></span>
							</div>
							{{ form.studying }}
						</div>
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-hashtag"></i></span>
							</div>
							{{ form.branch }}
						</div>
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-hashtag"></i></span>
							</div>
							{{ form.persuingyear }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{ form.email }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password1 }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password2 }}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>
		                {{ form.errors }}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
	<script>
	$("#id_rollNumber").on('change',function() {
		console.log("hi welcome")
		console.log($(this).val())
		url = $('#signupform').attr('data-url');
		const roll_num = $(this).val();
		console.log(roll_num);
		$.ajax({
			url: url,
			data: {'roll_num': roll_num},
			success:function(data){
				console.log("hi")
				console.log(data)
				console.log(data.name)
				$('#id_username').val(data.name);
				$('#id_studying').val(data.degree);
				$('#id_branch').val(data.branch);
				$('#id_persuingyear').val(data.persuing_year);
				$('#id_email').val(data.email_id)
				}
			});	
		
	});
	</script>
</body>

</html>




library/templates/subCat_dropdown_list.html
<option value="">---------</option>
{% for sc in subCats %}
<option value="{{ sc.pk }}">{{ sc.sub_category_name }}</option>
{% endfor %}